---
- shell: cat ansible/tasks/backup/backupip.txt
- shell: head -n1 /var/lib/awx/projects/tata/kvm/ansible/tasks/backup/backupip.txt
  register: ip 
- lineinfile:
   path: /var/lib/awx/projects/tata/kvm/ansible/tasks/backup/backup.csv
   regexp: '^{{ ip.stdout }}'
   line: '{{ip.stdout}},free'
- shell: 'echo "$(tail -n +2 /var/lib/awx/projects/tata/kvm/ansible/tasks/backup/backupip.txt)" > /var/lib/awx/projects/tata/kvm/ansible/tasks/backup/backupip.txt' 
